[DB]
	DbName      = "ping"
	Address     = "127.0.0.1"
	Port        = "27017"
[SMTP]
	Email 		= "some-address@gmail.com"
	Password 	= "securepassword"
	Server 		= "smtp.gmail.com"
	Port 		= "587"
Emails	= [
		"email@one.com",
		"email@two.com"
	]